#!/bin/sh
#
# Xcode Cloud runs this immediately after cloning, before it resolves the scheme
# it was asked to build.
#
# It exists because THERE IS NO PROJECT IN A FRESH CLONE. `Hive.xcodeproj` is
# generated by XcodeGen from `project.yml` and is gitignored (`.gitignore` line 1),
# so a clone contains sources, a manifest, and no target to build. Every other
# consumer of this repo generates it by hand; Xcode Cloud cannot, so it happens
# here. Same reason the schemes are absent — they live inside the generated
# project, and Xcode Cloud resolves the scheme by NAME after this script runs.
#
# `set -e` is the whole error handling: a failure to generate must fail the build
# loudly rather than hand Xcode Cloud a repository it will report as "scheme not
# found", which reads as a misconfigured workflow rather than a broken script.
set -e

echo "--- Installing XcodeGen"
# Homebrew is present in the Xcode Cloud environment. Unpinned deliberately:
# pinning a formula version here rots faster than the generator's own output,
# and `project.yml` is written against XcodeGen's stable surface. The one place
# this repo depends on a version detail is the app icon (see project.yml), and
# that entry is written to be correct for a generator that knows `.icon` and for
# one that does not.
brew install xcodegen

echo "--- Generating Hive.xcodeproj"
# Xcode Cloud runs this with `ci_scripts` as the working directory and exports
# the repository root here, so the `cd` is required rather than cosmetic. The
# `:?` is: unset, `cd ""` succeeds and stays put, which would generate the
# project into whatever directory the script happened to start in and fail much
# later as "scheme not found". Fail here, where the message is the cause.
cd "${CI_PRIMARY_REPOSITORY_PATH:?must be set — Xcode Cloud exports it; set it by hand to run this locally}"
xcodegen generate

echo "--- Generated:"
ls -d Hive.xcodeproj
ls Hive.xcodeproj/xcshareddata/xcschemes
