#!/bin/sh
#
# Xcode Cloud runs this immediately after cloning, before it resolves the scheme
# it was asked to build.
#
# It exists because THERE IS NO PROJECT IN A FRESH CLONE. `Hive.xcodeproj` is
# generated by XcodeGen from `project.yml` and is gitignored (`.gitignore` line 1),
# so a clone contains sources, a manifest, and no target to build. Every other
# consumer of this repo generates it by hand; Xcode Cloud cannot, so it happens
# here. Same reason the schemes are absent — they live inside the generated
# project, and Xcode Cloud resolves the scheme by NAME after this script runs.
#
# A clone is missing a second thing for the same reason: the `Package.resolved`
# Xcode Cloud requires lives inside that same generated project. Both gaps are
# closed below, in the order the build reads them — the project is generated,
# then the committed pins are copied into it.
#
# `set -e` is the whole error handling: a failure to generate must fail the build
# loudly rather than hand Xcode Cloud a repository it will report as "scheme not
# found", which reads as a misconfigured workflow rather than a broken script.
set -e

echo "--- Installing XcodeGen"
# Homebrew is present in the Xcode Cloud environment. Unpinned deliberately:
# pinning a formula version here rots faster than the generator's own output,
# and `project.yml` is written against XcodeGen's stable surface. The one place
# this repo depends on a version detail is the app icon (see project.yml), and
# that entry is written to be correct for a generator that knows `.icon` and for
# one that does not.
brew install xcodegen

echo "--- Generating Hive.xcodeproj"
# Xcode Cloud runs this with `ci_scripts` as the working directory and exports
# the repository root here, so the `cd` is required rather than cosmetic. The
# `:?` is: unset, `cd ""` succeeds and stays put, which would generate the
# project into whatever directory the script happened to start in and fail much
# later as "scheme not found". Fail here, where the message is the cause.
cd "${CI_PRIMARY_REPOSITORY_PATH:?must be set — Xcode Cloud exports it; set it by hand to run this locally}"
xcodegen generate

echo "--- Generated:"
ls -d Hive.xcodeproj
ls Hive.xcodeproj/xcshareddata/xcschemes

echo "--- Installing Package.resolved"
# Xcode Cloud builds with automatic package resolution disabled, and reads the
# versions it may fetch from a `Package.resolved` inside the generated project's
# workspace. A clone cannot carry that file: it lives inside the gitignored
# `Hive.xcodeproj`, and `Package.resolved` is gitignored in its own right. So it
# is copied in from `Config/Package.resolved`, which IS committed (see the
# negation in `.gitignore`).
#
# It is COPIED rather than resolved here. Resolving was tried and does not work:
# the flag is not scoped to Xcode Cloud's own build command, it is in force for
# every `xcodebuild` on the machine, so `xcodebuild -resolvePackageDependencies`
# is refused with the same message it was meant to prevent and the script dies
# with exit 74 (build 29). Nothing run from this script can resolve. Handing the
# build a finished file is the only move available.
#
# The cost is that `Config/Package.resolved` is a second place to update when a
# dependency version changes — `make pins` regenerates it, and a stale one fails
# the build here rather than silently building the wrong version.
mkdir -p Hive.xcodeproj/project.xcworkspace/xcshareddata/swiftpm
cp Config/Package.resolved Hive.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

echo "--- Installed:"
ls -l Hive.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
